name: Test

# on:
#   pull_request:
#     branches:
#       - main

#   push:
#     branches:
#       - main

#     tags:
#       - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check types
        run: npm run type-check

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm test
